# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7f5d218f1bb5406d6cdcdeb55a910ef2f4e4b73967c732940ca5be7f1cd879c109963acfc38d390310cd7778aef024884f4e67b280e627ffd31675bbf1aacf6

test:
  secret_key_base: 327c310a55577f5f45e0d6ba163ec2674e734e08e7f71767770abfb2619d8b9e18b0b436f8fa11f215f2a8f63e745000434d3916e5b43a4e9a8ae6d8f7ebcb62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
